# Generated by Django 2.1 on 2018-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('tvm', 'Thiruvananthapuram'), ('ptm', 'Pathanamthitta'), ('alp', 'Alappuzha'), ('ktm', 'Kottayam'), ('idk', 'Idukki'), ('mpm', 'Malappuram'), ('koz', 'Kozhikode'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('pkd', 'Palakkad'), ('tcr', 'Thrissur'), ('ekm', 'Ernakulam'), ('kol', 'Kollam')], max_length=15)),
                ('location', models.CharField(max_length=500)),
                ('requestee', models.CharField(max_length=100)),
                ('requestee_phone', models.CharField(max_length=10)),
                ('needwater', models.BooleanField()),
                ('needfood', models.BooleanField()),
                ('needcloth', models.BooleanField()),
                ('needmed', models.BooleanField()),
                ('needothers', models.CharField(max_length=500)),
                ('status', models.BooleanField()),
                ('supply_details', models.CharField(max_length=100)),
            ],
        ),
    ]
