# Generated by Django 2.1 on 2018-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_request_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='needothers',
            field=models.CharField(max_length=500, verbose_name='Other needs'),
        ),
    ]
