# Generated by Django 2.1 on 2018-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180811_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
