# Generated by Django 2.1 on 2018-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20180811_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='needkit_util',
            field=models.BooleanField(default=False, verbose_name='Kitchen utencil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='needcloth',
            field=models.BooleanField(verbose_name='Clothing'),
        ),
        migrations.AlterField(
            model_name='request',
            name='needfood',
            field=models.BooleanField(verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='request',
            name='needmed',
            field=models.BooleanField(verbose_name='Medicine'),
        ),
        migrations.AlterField(
            model_name='request',
            name='needwater',
            field=models.BooleanField(verbose_name='Water'),
        ),
    ]
