# Generated by Django 2.1 on 2018-08-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20180811_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='detailcloth',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required clothing'),
        ),
        migrations.AddField(
            model_name='request',
            name='detailfood',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required food'),
        ),
        migrations.AddField(
            model_name='request',
            name='detailkit_util',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required kitchen utensil'),
        ),
        migrations.AddField(
            model_name='request',
            name='detailmed',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required medicine'),
        ),
        migrations.AddField(
            model_name='request',
            name='detailtoilet',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required toileteries'),
        ),
        migrations.AddField(
            model_name='request',
            name='detailwater',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required water'),
        ),
        migrations.AlterField(
            model_name='request',
            name='needkit_util',
            field=models.BooleanField(verbose_name='Kitchen utensil'),
        ),
    ]
