# Generated by Django 2.1 on 2018-08-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_contributors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributors',
            new_name='Contributor',
        ),
    ]
