# Generated by Django 2.1 on 2018-08-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20180812_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistrictNeeds',
            new_name='DistrictNeed',
        ),
    ]
