# Generated by Django 2.1 on 2018-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20180812_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ful', 'Fullfilled')], default='new', max_length=10),
        ),
    ]
