# Generated by Django 2.1 on 2018-08-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20180813_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtneed',
            name='needs',
            field=models.TextField(verbose_name='Items required'),
        ),
    ]
